export default {
  products: [
    {
      _id: '1',
      name: 'pet',
      category: 'pet',
      image: '/images/p1.jpg',
      price: 60,
      brand: 'pet',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '2',
      name: 'pet',
      category: 'pet',
      image: '/images/d1.jpg',
      price: 50,
      brand: 'pet',
      rating: 4.2,
      numReviews: 5,
    },
    {
      _id: '3',
      name: 'pet',
      category: 'pet',
      image: '/images/d1.jpg',
      price: 70,
      brand: '',
      rating: 4.5,
      numReviews: 8,
    },
    {
      _id: '4',
      name: 'pet',
      category: 'pet',
      image: '/images/d1.jpg',
      price: 70,
      brand: 'pet',
      rating: 4.5,
      numReviews: 8,
    },
  ],
};
